server:
  port: 8515

spring:
  application:
    name: service-pay
  cloud:
    nacos:
      discovery:
        #TODO 将localhost修改成自己的ip
        server-addr: localhost:8848
  # 配置数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #TODO 将192.168.10.100修改成自己的ip
    url: jdbc:mysql://192.168.10.100:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
  # Redis的相关配置
  data:
    redis:
      #TODO 将192.168.10.100修改成自己的ip
      host: 192.168.10.100
      port: 6379
  config:
    import: application-alipay.yml

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml