server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        #TODO 将localhost修改成自己的ip
        server-addr: localhost:8848
  data:
    redis:
      #TODO 将192.168.10.100修改成自己的ip
      host: 192.168.10.100
      port: 6379